#!/bin/bash

npm prune
npm shrinkwrap
files=`git diff --cached --name-status`
re="npm-shrinkwrap.json"
if [[ $files =~ $re ]]
then
  echo "Adding npm-shrinkwrap.json"
  git add npm-shrinkwrap.json
fi
